sudo: required
services: docker
language: go

go:
  - 1.5.2

before_install:
  - sudo apt-get update -qq && sudo apt-get -y --force-yes -o Dpkg::Options::="--force-confnew" install $APT_DOCKER_PKG && docker -v

script: bin/docker.sh ci $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST
